### ISSUE TITLE
Clear pending block if failed locally

### ISSUE THREAD

**Issue by ndr-ds** [linera-io/linera-protocol#2906]
If a block fails locally before being sent to the validators (for whatever reason), we currently don't clear the pending block. That means that we'll basically "brick" that chain client, as every block that we try to propose using it, will try (and fail) to propose the pending block again.
If we fail locally we should clear the pending block

**Comment by afck** [comment]
I now think it was a mistake (_my_ mistake!) to use the "pending block" as the "intended block", and to set it as early as we do now. Clearing it again is dangerous if we aren't 100% sure that we never sent it to a validators.

We should restructure the code so that we set the pending block only after successfully proposing it in the local node.
