### ISSUE TITLE
The Relationship Between Canonical and Signature in BCS

### ISSUE THREAD

**Issue by tjchern** [linera-io/linera-protocol#2992]
Hello Monsieur Baudet @ma2bd 
I am really confused about Why must the serialized object for signing be canonical.
The process of signing involves the sender's object being serialized into a byte array, which is then signed. The data transmitted is just byte data, and when the receiver verifies the signature, they simply retrieve the same byte data and perform signature verification. It seems like there is no connection to canonical at all during this process.
So, what is the actual impact of canonical on signature verification ?
I look forward to your response. Thank you!

**Comment by ma2bd** [comment]
Generally speaking, in a security protocol, when you need to sign or hash data, you can either write a data hasher directly or use a serializer function to send bytes to the hashing function. The first option is error-prone and you could end up with vulnerabilities (hash collisions) that are hard to prevent by testing. Using a serializer is more reliable because we can test it by serializing then deserializing data. However, it is important that the serialization is deterministic. The best way to implement and test this is by making the deserialization stricter: for instance in BCS `true` serializes to `1u8` and `2u8` is not accepted as valid bytes for `true` (only `1u8` is).
