### ISSUE TITLE
Audit all `Vec::new` in the code and change to `Vec::with_capacity` if possible

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#436]

**Comment by duguorong009** [comment]
@ma2bd 
I'd like to pick the issue.
Can you take a look at the PR #2373 ?

**Comment by afck** [comment]
We had a discussion and decided to not do this for now, because it makes it easy to allocate too much in the end: E.g. one can overlook or insert `break` statements of make the `push` conditional without updating the `with_capacity`.

In some places we could use `Iterator::collect` instead: For `ExactSizeIterator`s that automatically allocates the right amount. (But only where that doesn't make the code less readable.)
