### ISSUE TITLE
Would it be better to change server to validator?

### ISSUE THREAD

**Issue by firedpeanut** [linera-io/linera-protocol#845]
rename linera-validator
https://github.com/linera-io/linera-protocol/blob/3b30d39329a378ca69ffe8e260ad7cb30be3a981/linera-service/Cargo.toml#L85

**Comment by christos-h** [comment]
Hi @firedpeanut. That's a good question. A server is not precisely a validator. A validator is a logical unit and is comprised of (for now) a *proxy* which acts as an ingress and load balancer as well as one or more *shards* (also called servers).

We will probably start to group proxies and servers together into a single unit we ship (using containerization or otherwise) in the future.

Feel free to close the issue if this answers your question.

**Comment by firedpeanut** [comment]
I see. thank you.
